### ISSUE TITLE
[PE-D][Tester B] Tooltip for `addModule` is inaccurate.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-F12-3/tp#161] opened 2023-11-03 20:08 UTC
`Module codes should only contain alphanumeric characters and it should be 5-6 characters`

How to reproduce:
`addModule m/ASFCIASFKJKCSAOCSAPCX02`

Expected behaviour:
The above should not be valid input.

Current behaviour:
It is allowed.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: et-irl/ped#13

**Comment by supermii2** [comment] 2023-11-04 12:50
Duplicate of #145

**Comment by jacksonyuan256** [comment] 2023-11-08 08:50
Closed - see Pull Request #218  Fix bugs for delete module

**Closed by jacksonyuan256** 2023-11-08 08:50 UTC
Labels: duplicate
